name: hnh_app
description: A Flutter-based commute management system for companies and employees.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2

flutter:
  uses-material-design: true
